import { Component, Input } from '@angular/core'
import {
  UiTimelineComponent,
  UiTimelineContentComponent,
  UiTimelineDateComponent,
  UiTimelineDescriptionComponent,
  UiTimelineHeaderComponent,
  UiTimelineItemComponent,
  UiTimelineMediaComponent,
  UiTimelineSeparatorComponent,
  UiTimelineTitleComponent,
} from '../../../../../packages/registry-angular/components/timeline/timeline.component'
import {
  UiAvatarComponent,
  UiAvatarFallbackComponent,
} from '../../../../../packages/registry-angular/components/avatar/avatar.component'
import { UiBadgeComponent } from '../../../../../packages/registry-angular/components/badge/badge.component'
import { UiButtonComponent } from '../../../../../packages/registry-angular/components/button/button.component'
import {
  UiCardComponent,
  UiCardContentComponent,
  UiCardHeaderComponent,
  UiCardTitleComponent,
} from '../../../../../packages/registry-angular/components/card/card.component'
import {
  UiTabsComponent,
  UiTabsListComponent,
  UiTabsTriggerComponent,
} from '../../../../../packages/registry-angular/components/tabs/tabs.component'

/**
 * Angular demo for the timeline page. Mirrors demos/react/timeline.tsx story by story (the
 * React data arrays are unrolled into static markup; generated by scratchpad t23/timeline_gen.py).
 */
@Component({
  selector: 'angular-timeline-demo',
  standalone: true,
  host: { class: 'block' },
  imports: [
    UiTimelineComponent,
    UiTimelineItemComponent,
    UiTimelineMediaComponent,
    UiTimelineSeparatorComponent,
    UiTimelineContentComponent,
    UiTimelineHeaderComponent,
    UiTimelineTitleComponent,
    UiTimelineDescriptionComponent,
    UiTimelineDateComponent,
    UiAvatarComponent,
    UiAvatarFallbackComponent,
    UiBadgeComponent,
    UiButtonComponent,
    UiCardComponent,
    UiCardHeaderComponent,
    UiCardTitleComponent,
    UiCardContentComponent,
    UiTabsComponent,
    UiTabsListComponent,
    UiTabsTriggerComponent,
  ],
  template: `
    @switch (story) {
      @case ('Default') {
        <div ui-timeline class="max-w-md">
          <div ui-timeline-item>
            <div ui-timeline-media></div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Release v2.4.0 tagged</h3>
                <time ui-timeline-date>12m ago</time>
              </div>
              <p ui-timeline-description>Tagged on main and artifacts pushed to staging registry.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media></div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Automated test suites passed</h3>
                <time ui-timeline-date>35m ago</time>
              </div>
              <p ui-timeline-description>All 84 unit, integration, and cross-framework parity tests passed.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media></div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Security audit cleared</h3>
                <time ui-timeline-date>50m ago</time>
              </div>
              <p ui-timeline-description>Static analysis and dependency vulnerability scan cleared with 0 findings.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media></div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Pull request approved</h3>
                <time ui-timeline-date>1h ago</time>
              </div>
              <p ui-timeline-description>Changes reviewed and signed off by core platform maintainers.</p>
            </div>
          </div>
        </div>
      }
      @case ('Icon markers') {
        <div ui-timeline class="max-w-md">
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-git-commit-horizontal"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="3" />
                <line x1="3" x2="9" y1="12" y2="12" />
                <line x1="15" x2="21" y1="12" y2="12" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Commit pushed to main</h3>
                <time ui-timeline-date>10:14 AM</time>
              </div>
              <p ui-timeline-description>feat(auth): enable WebAuthn biometric passkey authentication</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-git-pull-request"
                aria-hidden="true"
              >
                <circle cx="18" cy="18" r="3" />
                <circle cx="6" cy="6" r="3" />
                <path d="M13 6h3a2 2 0 0 1 2 2v7" />
                <line x1="6" x2="6" y1="9" y2="21" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Pull request merged</h3>
                <time ui-timeline-date>10:18 AM</time>
              </div>
              <p ui-timeline-description>PR #892 merged into main with 3 approvals</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-package"
                aria-hidden="true"
              >
                <path
                  d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"
                />
                <path d="M12 22V12" />
                <polyline points="3.29 7 12 12 20.71 7" />
                <path d="m7.5 4.27 9 5.15" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Container image packaged</h3>
                <time ui-timeline-date>10:22 AM</time>
              </div>
              <p ui-timeline-description>Docker image built and pushed digest to registry</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Production deploy completed</h3>
                <time ui-timeline-date>10:25 AM</time>
              </div>
              <p ui-timeline-description>Live traffic switched across all 18 edge CDN clusters</p>
            </div>
          </div>
        </div>
      }
      @case ('Status indicators') {
        <div ui-timeline class="max-w-md">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Static Analysis & Lint</h3>
                <span ui-badge variant="secondary" class="text-xs">14s</span>
              </div>
              <p ui-timeline-description>ESLint and TypeScript strict typechecks passed</p>
            </div>
          </div>
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Automated Test Suites</h3>
                <span ui-badge variant="secondary" class="text-xs">38s</span>
              </div>
              <p ui-timeline-description>128 unit and browser integration tests completed</p>
            </div>
          </div>
          <div ui-timeline-item status="current">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle-dot"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
                <circle cx="12" cy="12" r="1" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Container Image Build</h3>
                <span ui-badge variant="default" class="text-xs">In progress</span>
              </div>
              <p ui-timeline-description>Compiling multi-arch Docker image (layer 8/12)</p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Canary Rollout (10%)</h3>
                <span ui-badge variant="outline" class="text-xs">Pending</span>
              </div>
              <p ui-timeline-description>Queued behind container build completion</p>
            </div>
          </div>
        </div>
      }
      @case ('Status colors') {
        <div ui-timeline class="max-w-md">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Build #482</h3>
              <p ui-timeline-description>Compiled successfully in 38s</p>
            </div>
          </div>
          <div ui-timeline-item status="info">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Build #483</h3>
              <p ui-timeline-description>Integration test passed in 42s</p>
            </div>
          </div>
          <div ui-timeline-item status="error">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-triangle-alert"
                aria-hidden="true"
              >
                <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
                <path d="M12 9v4" />
                <path d="M12 17h.01" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Build #484</h3>
              <p ui-timeline-description>Lint check failed at app/utils.ts</p>
            </div>
          </div>
          <div ui-timeline-item status="warning">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle-dashed"
                aria-hidden="true"
              >
                <path d="M10.1 2.182a10 10 0 0 1 3.8 0" />
                <path d="M13.9 21.818a10 10 0 0 1-3.8 0" />
                <path d="M17.609 3.721a10 10 0 0 1 2.69 2.7" />
                <path d="M2.182 13.9a10 10 0 0 1 0-3.8" />
                <path d="M20.279 17.609a10 10 0 0 1-2.7 2.69" />
                <path d="M21.818 10.1a10 10 0 0 1 0 3.8" />
                <path d="M3.721 6.391a10 10 0 0 1 2.7-2.69" />
                <path d="M6.391 20.279a10 10 0 0 1-2.69-2.7" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Build #485</h3>
              <p ui-timeline-description>Worker runner high memory load</p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-clock"
                aria-hidden="true"
              >
                <path d="M12 6v6l4 2" />
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Build #486</h3>
              <p ui-timeline-description>Queued · waiting for runner slot</p>
            </div>
          </div>
        </div>
      }
      @case ('Side: right') {
        <div ui-timeline side="right" class="max-w-md">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-credit-card"
                aria-hidden="true"
              >
                <rect width="20" height="14" x="2" y="5" rx="2" />
                <line x1="2" x2="22" y1="10" y2="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Order placed</h3>
              <time ui-timeline-date>May 1</time>
            </div>
          </div>
          <div ui-timeline-item status="info">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-package"
                aria-hidden="true"
              >
                <path
                  d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"
                />
                <path d="M12 22V12" />
                <polyline points="3.29 7 12 12 20.71 7" />
                <path d="m7.5 4.27 9 5.15" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Packed</h3>
              <time ui-timeline-date>May 2</time>
            </div>
          </div>
          <div ui-timeline-item status="current">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-truck"
                aria-hidden="true"
              >
                <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
                <path d="M15 18H9" />
                <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
                <circle cx="17" cy="18" r="2" />
                <circle cx="7" cy="18" r="2" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Out for delivery</h3>
              <time ui-timeline-date>May 3</time>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Delivered</h3>
              <time ui-timeline-date>May 4</time>
            </div>
          </div>
        </div>
      }
      @case ('Alternating sides') {
        <div ui-timeline align="center" class="max-w-2xl">
          <div ui-timeline-item>
            <div ui-timeline-media variant="dot"></div>
            <div ui-timeline-content class="space-y-1">
              <h3 ui-timeline-title>Q1 2026 — Core Architecture</h3>
              <time ui-timeline-date>Jan 2026</time>
              <p ui-timeline-description>Distributed runtime RFC approved and core system interfaces defined.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="dot"></div>
            <div ui-timeline-content class="space-y-1">
              <h3 ui-timeline-title>Q2 2026 — Developer Preview</h3>
              <time ui-timeline-date>Apr 2026</time>
              <p ui-timeline-description>First cohort of 50 enterprise design partners onboarded to SDK.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="dot"></div>
            <div ui-timeline-content class="space-y-1">
              <h3 ui-timeline-title>Q3 2026 — Multi-Region Availability</h3>
              <time ui-timeline-date>Jul 2026</time>
              <p ui-timeline-description>Zero-downtime replication active across US, EU, and APAC clusters.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="dot"></div>
            <div ui-timeline-content class="space-y-1">
              <h3 ui-timeline-title>Q4 2026 — General Availability</h3>
              <time ui-timeline-date>Oct 2026</time>
              <p ui-timeline-description>Public launch with self-service signups and enterprise SLA.</p>
            </div>
          </div>
        </div>
      }
      @case ('Horizontal') {
        <div ui-timeline direction="horizontal" class="w-full overflow-x-auto py-2">
          <div ui-timeline-item status="success" class="min-w-36">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-credit-card"
                aria-hidden="true"
              >
                <rect width="20" height="14" x="2" y="5" rx="2" />
                <line x1="2" x2="22" y1="10" y2="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title class="text-xs font-semibold">Order placed</h3>
              <time ui-timeline-date class="text-xs">May 1</time>
            </div>
          </div>
          <div ui-timeline-item status="info" class="min-w-36">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-package"
                aria-hidden="true"
              >
                <path
                  d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"
                />
                <path d="M12 22V12" />
                <polyline points="3.29 7 12 12 20.71 7" />
                <path d="m7.5 4.27 9 5.15" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title class="text-xs font-semibold">Packed</h3>
              <time ui-timeline-date class="text-xs">May 2</time>
            </div>
          </div>
          <div ui-timeline-item status="current" class="min-w-36">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-truck"
                aria-hidden="true"
              >
                <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
                <path d="M15 18H9" />
                <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
                <circle cx="17" cy="18" r="2" />
                <circle cx="7" cy="18" r="2" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title class="text-xs font-semibold">Out for delivery</h3>
              <time ui-timeline-date class="text-xs">May 3</time>
            </div>
          </div>
          <div ui-timeline-item status="muted" class="min-w-36">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title class="text-xs font-semibold">Delivered</h3>
              <time ui-timeline-date class="text-xs">May 4</time>
            </div>
          </div>
        </div>
      }
      @case ('Avatar markers') {
        <div ui-timeline class="max-w-lg">
          <div ui-timeline-item>
            <div ui-timeline-media variant="avatar">
              <span ui-avatar class="size-8"><span ui-avatar-fallback class="text-xs font-medium">SC</span></span>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <div class="flex items-center gap-1.5 text-sm">
                  <span class="font-semibold">Sarah Chen</span
                  ><span class="text-muted-foreground">opened pull request #402</span>
                </div>
                <time ui-timeline-date>12m ago</time>
              </div>
              <p ui-timeline-description>
                feat(tokens): add support for OKLCH color spaces and dynamic contrast clamping
              </p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="avatar">
              <span ui-avatar class="size-8"><span ui-avatar-fallback class="text-xs font-medium">MV</span></span>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <div class="flex items-center gap-1.5 text-sm">
                  <span class="font-semibold">Marcus Vance</span
                  ><span class="text-muted-foreground">approved pull request with comments</span>
                </div>
                <time ui-timeline-date>8m ago</time>
              </div>
              <p ui-timeline-description>Verified visual rendering and responsive layout across desktop and mobile.</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="avatar">
              <span ui-avatar class="size-8"><span ui-avatar-fallback class="text-xs font-medium">ER</span></span>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <div class="flex items-center gap-1.5 text-sm">
                  <span class="font-semibold">Elena Rostova</span
                  ><span class="text-muted-foreground">merged into main and generated changelog</span>
                </div>
                <time ui-timeline-date>Just now</time>
              </div>
              <p ui-timeline-description>Tagged v2.4.1 release candidate and published to edge nodes.</p>
            </div>
          </div>
        </div>
      }
      @case ('Compact density') {
        <div ui-timeline density="compact" class="max-w-md">
          <div ui-timeline-item>
            <div ui-timeline-separator></div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2 text-xs">
                <span class="text-muted-foreground font-mono">14:22:05</span
                ><span class="text-foreground">API secret key rotated for staging-worker</span>
              </div>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-separator></div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2 text-xs">
                <span class="text-muted-foreground font-mono">14:18:40</span
                ><span class="text-foreground">User permissions updated for admin_812</span>
              </div>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-separator></div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2 text-xs">
                <span class="text-muted-foreground font-mono">14:05:12</span
                ><span class="text-foreground">SSO session authenticated via Okta</span>
              </div>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-separator></div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2 text-xs">
                <span class="text-muted-foreground font-mono">13:52:19</span
                ><span class="text-foreground">Webhook endpoint verified: /api/v1/billing</span>
              </div>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-separator></div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2 text-xs">
                <span class="text-muted-foreground font-mono">13:40:02</span
                ><span class="text-foreground">IP whitelist rule updated for eu-west-1</span>
              </div>
            </div>
          </div>
        </div>
      }
      @case ('Comfortable density') {
        <div ui-timeline density="comfortable" class="max-w-md">
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-calendar"
                aria-hidden="true"
              >
                <path d="M8 2v4" />
                <path d="M16 2v4" />
                <rect width="18" height="18" x="3" y="4" rx="2" />
                <path d="M3 10h18" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Project Kickoff</h3>
              <time ui-timeline-date>Jan 15, 2026</time>
              <p ui-timeline-description>Scope alignment & team ramp-up</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-git-commit-horizontal"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="3" />
                <line x1="3" x2="9" y1="12" y2="12" />
                <line x1="15" x2="21" y1="12" y2="12" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Internal Beta Testing</h3>
              <time ui-timeline-date>Feb 20, 2026</time>
              <p ui-timeline-description>Dogfooding with internal teams</p>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <h3 ui-timeline-title>Security Audit & Compliance</h3>
              <time ui-timeline-date>Mar 10, 2026</time>
              <p ui-timeline-description>SOC2 Type II sign-off</p>
            </div>
          </div>
        </div>
      }
      @case ('Outline marker & dashed connector') {
        <div ui-timeline class="max-w-lg">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="outline" lineStyle="dashed">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Specification Approved</h3>
                <span ui-badge variant="outline" class="text-xs">Phase 1</span>
              </div>
              <time ui-timeline-date>September 15, 2026</time>
              <p ui-timeline-description>System architecture and OpenAPI spec signed off by engineering leads.</p>
            </div>
          </div>
          <div ui-timeline-item status="info">
            <div ui-timeline-media variant="outline" lineStyle="dashed">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-git-commit-horizontal"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="3" />
                <line x1="3" x2="9" y1="12" y2="12" />
                <line x1="15" x2="21" y1="12" y2="12" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Alpha Deployment</h3>
                <span ui-badge variant="secondary" class="text-xs">In Progress</span>
              </div>
              <time ui-timeline-date>September 18, 2026</time>
              <p ui-timeline-description>
                Continuous integration runner deployed artifacts to staging sandbox for QA smoke tests.
              </p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="outline" lineStyle="dashed">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-rocket"
                aria-hidden="true"
              >
                <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
                <path
                  d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"
                />
                <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
                <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Production Rollout</h3>
                <span ui-badge variant="outline" class="text-xs">Scheduled</span>
              </div>
              <time ui-timeline-date>October 1, 2026</time>
              <p ui-timeline-description>Canary release at 10% traffic threshold before universal cutover.</p>
            </div>
          </div>
        </div>
      }
      @case ('Checklist (done / pending)') {
        <div ui-timeline class="max-w-lg">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title class="text-muted-foreground line-through">Create your workspace</h3>
                <span ui-badge variant="secondary" class="text-xs">Done</span>
              </div>
              <p ui-timeline-description>Pick a name and invite your core team.</p>
            </div>
          </div>
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title class="text-muted-foreground line-through">Connect a data source</h3>
                <span ui-badge variant="secondary" class="text-xs">Done</span>
              </div>
              <p ui-timeline-description>PostgreSQL, MySQL, or ClickHouse data warehouse.</p>
            </div>
          </div>
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title class="text-muted-foreground line-through">Configure billing</h3>
                <span ui-badge variant="secondary" class="text-xs">Done</span>
              </div>
              <p ui-timeline-description>Add a payment method to unlock production quotas.</p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title>Invite your first member</h3>
                <span ui-badge variant="outline" class="text-xs">Pending</span>
              </div>
              <p ui-timeline-description>Send a magic-link invitation via email.</p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title>Publish your first dashboard</h3>
                <span ui-badge variant="outline" class="text-xs">Pending</span>
              </div>
              <p ui-timeline-description>Pick a template or start from blank canvas.</p>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon" coloredConnector>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div class="flex items-center gap-2">
                <h3 ui-timeline-title>Set up alerts</h3>
                <span ui-badge variant="outline" class="text-xs">Pending</span>
              </div>
              <p ui-timeline-description>Configure Slack, email, or PagerDuty webhooks.</p>
            </div>
          </div>
        </div>
      }
      @case ('Mixed content') {
        <div ui-timeline class="max-w-lg">
          <div ui-timeline-item status="info">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-rocket"
                aria-hidden="true"
              >
                <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
                <path
                  d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"
                />
                <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
                <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <time ui-timeline-date>May 1, 2026 · 09:14</time>
              <h3 ui-timeline-title>v2.0 released</h3>
              <p ui-timeline-description>
                Major release with the new theming engine, 12 new components, and improved CLI ergonomics.
              </p>
              <div class="flex gap-2 pt-1">
                <button ui-button size="sm" variant="outline">Read changelog</button
                ><button ui-button size="sm" variant="ghost">Dismiss</button>
              </div>
            </div>
          </div>
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-git-commit-horizontal"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="3" />
                <line x1="3" x2="9" y1="12" y2="12" />
                <line x1="15" x2="21" y1="12" y2="12" />
              </svg>
            </div>
            <div ui-timeline-content>
              <time ui-timeline-date>May 2, 2026 · 14:02</time>
              <h3 ui-timeline-title>Pull request merged</h3>
              <p ui-timeline-description>feat(carousel): add vertical orientation and indicator pagination · #248</p>
              <div class="flex gap-2 pt-1"><button ui-button size="sm" variant="outline">View PR</button></div>
            </div>
          </div>
          <div ui-timeline-item>
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-file-text"
                aria-hidden="true"
              >
                <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                <path d="M10 9H8" />
                <path d="M16 13H8" />
                <path d="M16 17H8" />
              </svg>
            </div>
            <div ui-timeline-content>
              <time ui-timeline-date>May 3, 2026 · 11:30</time>
              <h3 ui-timeline-title>Docs updated</h3>
              <p ui-timeline-description>
                Component preview pages now extract demo source automatically with the Story block format.
              </p>
            </div>
          </div>
        </div>
      }
      @case ('Activity feed (day-grouped)') {
        <div class="max-w-2xl space-y-6">
          <div ui-tabs defaultValue="today">
            <div ui-tabs-list>
              <button ui-tabs-trigger value="today">Today</button><button ui-tabs-trigger value="week">Week</button
              ><button ui-tabs-trigger value="month">Month</button><button ui-tabs-trigger value="year">2026</button>
            </div>
          </div>
          <div>
            <h3 class="text-foreground mb-4 text-sm font-semibold">Jan 23, 2026</h3>
            <div ui-timeline>
              <div ui-timeline-item status="info">
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-message-square"
                    aria-hidden="true"
                  >
                    <path
                      d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"
                    />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <div class="flex items-center gap-2 text-sm">
                    <span class="font-semibold">Meeting with customer</span
                    ><span class="text-muted-foreground">· 10:45 AM</span>
                  </div>
                  <p ui-timeline-description>Discussed Q2 onboarding flow with Robert Fox.</p>
                  <div class="flex items-center gap-2 pt-1">
                    <span ui-avatar class="size-6"><span ui-avatar-fallback>RF</span></span
                    ><span class="text-muted-foreground text-xs">Robert Fox</span>
                  </div>
                </div>
              </div>
              <div ui-timeline-item>
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-clipboard-check"
                    aria-hidden="true"
                  >
                    <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
                    <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
                    <path d="m9 14 2 2 4-4" />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <div class="flex items-center gap-2">
                    <h3 ui-timeline-title>Project Delivery Preparation</h3>
                    <span ui-badge variant="secondary">In Progress</span>
                  </div>
                  <p ui-timeline-description>CRM Project deliverables and pre-flight checklist.</p>
                  <div class="flex items-center justify-between pt-1">
                    <div class="flex -space-x-2">
                      <span ui-avatar class="ring-background size-6 ring-2"><span ui-avatar-fallback>AB</span></span
                      ><span ui-avatar class="ring-background size-6 ring-2"><span ui-avatar-fallback>CD</span></span
                      ><span ui-avatar class="ring-background size-6 ring-2"><span ui-avatar-fallback>EF</span></span>
                    </div>
                    <span ui-badge variant="outline">CRM</span>
                  </div>
                </div>
              </div>
              <div ui-timeline-item>
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-file-text"
                    aria-hidden="true"
                  >
                    <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                    <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                    <path d="M10 9H8" />
                    <path d="M16 13H8" />
                    <path d="M16 17H8" />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <h3 ui-timeline-title>3 files were uploaded</h3>
                  <ul class="mt-1 space-y-1.5">
                    <li
                      class="border-border bg-muted/40 flex items-center justify-between rounded-md border px-3 py-1.5 text-sm"
                    >
                      <span class="flex items-center gap-2"
                        ><svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          stroke-width="2"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          class="lucide lucide-file-text text-muted-foreground size-4"
                          aria-hidden="true"
                        >
                          <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                          <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                          <path d="M10 9H8" />
                          <path d="M16 13H8" />
                          <path d="M16 17H8" /></svg
                        ><span class="font-medium">Project-Spec-v3.pdf</span></span
                      ><span class="text-muted-foreground text-xs">1.9 MB</span>
                    </li>
                    <li
                      class="border-border bg-muted/40 flex items-center justify-between rounded-md border px-3 py-1.5 text-sm"
                    >
                      <span class="flex items-center gap-2"
                        ><svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          stroke-width="2"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          class="lucide lucide-file-text text-muted-foreground size-4"
                          aria-hidden="true"
                        >
                          <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                          <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                          <path d="M10 9H8" />
                          <path d="M16 13H8" />
                          <path d="M16 17H8" /></svg
                        ><span class="font-medium">Hero-mockups.zip</span></span
                      ><span class="text-muted-foreground text-xs">18 KB</span>
                    </li>
                    <li
                      class="border-border bg-muted/40 flex items-center justify-between rounded-md border px-3 py-1.5 text-sm"
                    >
                      <span class="flex items-center gap-2"
                        ><svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          stroke-width="2"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          class="lucide lucide-file-text text-muted-foreground size-4"
                          aria-hidden="true"
                        >
                          <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                          <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                          <path d="M10 9H8" />
                          <path d="M16 13H8" />
                          <path d="M16 17H8" /></svg
                        ><span class="font-medium">Brand-system.css</span></span
                      ><span class="text-muted-foreground text-xs">20 KB</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h3 class="text-foreground mb-4 text-sm font-semibold">Jan 22, 2026</h3>
            <div ui-timeline>
              <div ui-timeline-item status="muted">
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-image"
                    aria-hidden="true"
                  >
                    <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
                    <circle cx="9" cy="9" r="2" />
                    <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <h3 ui-timeline-title>3 new design concepts shared</h3>
                  <p ui-timeline-description>Explore the homepage and dashboard explorations.</p>
                  <div class="grid grid-cols-3 gap-2 pt-2">
                    <div
                      class="border-border bg-muted/50 text-muted-foreground flex aspect-video items-center justify-center rounded-md border text-xs font-medium"
                    >
                      Concept A
                    </div>
                    <div
                      class="border-border bg-muted/50 text-muted-foreground flex aspect-video items-center justify-center rounded-md border text-xs font-medium"
                    >
                      Concept B
                    </div>
                    <div
                      class="border-border bg-muted/50 text-muted-foreground flex aspect-video items-center justify-center rounded-md border text-xs font-medium"
                    >
                      Concept C
                    </div>
                  </div>
                </div>
              </div>
              <div ui-timeline-item status="success">
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-database"
                    aria-hidden="true"
                  >
                    <ellipse cx="12" cy="5" rx="9" ry="3" />
                    <path d="M3 5V19A9 3 0 0 0 21 19V5" />
                    <path d="M3 12A9 3 0 0 0 21 12" />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <h3 ui-timeline-title>Database Backup Process Completed!</h3>
                  <p ui-timeline-description>All workspace snapshots are now mirrored to the EU region.</p>
                  <div class="pt-1"><button ui-button size="sm" variant="outline">Proceed</button></div>
                </div>
              </div>
              <div ui-timeline-item status="info">
                <div ui-timeline-media variant="icon">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-bell"
                    aria-hidden="true"
                  >
                    <path d="M10.268 21a2 2 0 0 0 3.464 0" />
                    <path
                      d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"
                    />
                  </svg>
                </div>
                <div ui-timeline-content>
                  <div class="text-sm">
                    <span class="font-semibold">New case #67890</span
                    ><span class="text-muted-foreground"> assigned to </span
                    ><span class="font-semibold">Cody Fisher</span>
                  </div>
                  <time ui-timeline-date>02:14 PM</time>
                </div>
              </div>
            </div>
          </div>
        </div>
      }
      @case ('Rich content cards') {
        <div ui-timeline class="max-w-lg">
          <div ui-timeline-item status="success">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-check"
                aria-hidden="true"
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Version 2.4.0 Released</h3>
                <span ui-badge variant="secondary">Production</span>
              </div>
              <time ui-timeline-date>September 20, 2026 · 11:30 AM</time>
              <div ui-card class="mt-2">
                <div ui-card-header class="pb-2">
                  <h3 ui-card-title class="text-sm font-medium">Core Enhancements</h3>
                </div>
                <div ui-card-content class="text-muted-foreground space-y-1.5 text-xs">
                  <p>• Added dual-framework timeline and calendar components.</p>
                  <p>• Calibrated optical alignment on dot and icon markers.</p>
                  <p>• Clean monochromatic surfaces across light and dark modes.</p>
                  <div class="pt-2">
                    <button ui-button size="sm" variant="outline" class="h-7 gap-1.5 text-xs">
                      View changelog<svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-external-link size-3"
                        aria-hidden="true"
                      >
                        <path d="M15 3h6v6" />
                        <path d="M10 14 21 3" />
                        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div ui-timeline-item status="muted">
            <div ui-timeline-media variant="icon">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
              </svg>
            </div>
            <div ui-timeline-content>
              <div ui-timeline-header>
                <h3 ui-timeline-title>Scheduled Database Maintenance</h3>
                <span ui-badge variant="outline">Upcoming</span>
              </div>
              <time ui-timeline-date>September 22, 2026 · 02:00 AM UTC</time>
              <p ui-timeline-description>
                Zero-downtime replication failover to warm standby nodes in the secondary availability zone.
              </p>
            </div>
          </div>
        </div>
      }
    }
  `,
})
export class AngularTimelineDemoComponent {
  @Input() story = 'Default'
}
