import { defineRegistryItem } from '../../lib/define-registry'

export default defineRegistryItem({
  name: 'kanban-task-board',
  type: 'registry:block',
  categories: ['productivity', 'dashboard', 'data'],
  description:
    'Full kanban task board surface: 4 status columns, drag-and-drop card movement with insertion indicator, board/list view toggle, search + priority + assignee filters, collapsible columns, click-to-open task detail Sheet (comments, subtasks, files), full-form Add Task Dialog with priority/assignee/due-date/tags/subtasks. Mega-block: ships 14 React files (KanbanBoard + 6 kanban-* views + 7 small badges/lists). Bind with columns/onColumnsChange; consumer owns the columns array so swapping the in-memory store for Drizzle/Postgres is a one-line change. Auto-pulls the use-kanban hook (types + configs + helpers) and kanban-data lib (seed columns).',
  files: [
    { path: 'KanbanBoard.tsx', target: 'components/blocks/kanban-task-board/KanbanBoard.tsx' },
    { path: 'SimpleKanban.tsx', target: 'components/blocks/kanban-task-board/SimpleKanban.tsx' },
    { path: 'KanbanCard.tsx', target: 'components/blocks/kanban-task-board/KanbanCard.tsx' },
    { path: 'KanbanColumn.tsx', target: 'components/blocks/kanban-task-board/KanbanColumn.tsx' },
    { path: 'KanbanListView.tsx', target: 'components/blocks/kanban-task-board/KanbanListView.tsx' },
    { path: 'KanbanTaskSheet.tsx', target: 'components/blocks/kanban-task-board/KanbanTaskSheet.tsx' },
    { path: 'KanbanAddTaskDialog.tsx', target: 'components/blocks/kanban-task-board/KanbanAddTaskDialog.tsx' },
    { path: 'KanbanToolbar.tsx', target: 'components/blocks/kanban-task-board/KanbanToolbar.tsx' },
    { path: 'PriorityBadge.tsx', target: 'components/blocks/kanban-task-board/PriorityBadge.tsx' },
    { path: 'DueDateBadge.tsx', target: 'components/blocks/kanban-task-board/DueDateBadge.tsx' },
    { path: 'TagBadge.tsx', target: 'components/blocks/kanban-task-board/TagBadge.tsx' },
    { path: 'UserAvatar.tsx', target: 'components/blocks/kanban-task-board/UserAvatar.tsx' },
    { path: 'SubtaskProgress.tsx', target: 'components/blocks/kanban-task-board/SubtaskProgress.tsx' },
    { path: 'SubtaskList.tsx', target: 'components/blocks/kanban-task-board/SubtaskList.tsx' },
    { path: 'CommentList.tsx', target: 'components/blocks/kanban-task-board/CommentList.tsx' },
  ],
  dependencies: ['lucide-react'],
  registryDependencies: [
    'https://uipkge.dev/r/use-kanban.json',
    'https://uipkge.dev/r/kanban-data.json',
    'https://uipkge.dev/r/page.json',
    'https://uipkge.dev/r/card.json',
    'https://uipkge.dev/r/button.json',
    'https://uipkge.dev/r/badge.json',
    'https://uipkge.dev/r/input.json',
    'https://uipkge.dev/r/label.json',
    'https://uipkge.dev/r/select.json',
    'https://uipkge.dev/r/sheet.json',
    'https://uipkge.dev/r/dialog.json',
    'https://uipkge.dev/r/popover.json',
    'https://uipkge.dev/r/calendar.json',
    'https://uipkge.dev/r/dropdown-menu.json',
    'https://uipkge.dev/r/tooltip.json',
    'https://uipkge.dev/r/avatar.json',
    'https://uipkge.dev/r/toggle-group.json',
    'https://uipkge.dev/r/rich-text-editor.json',
  ],
})
