import type { KanbanColumn } from '@/lib/use-kanban'
import { assignees, tagPresets } from '@/lib/use-kanban'

export function createInitialColumns(): KanbanColumn[] {
  return [
    {
      id: 'backlog',
      title: 'Backlog',
      color: 'text-muted-foreground',
      dotColor: 'bg-muted-foreground/60',
      tasks: [
        {
          id: 'HR-101',
          title: 'Draft updated remote work policy for Q3',
          description: 'Review current policy, benchmark competitors, propose updates',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [tagPresets.policy, tagPresets.compliance],
          dueDate: '2026-03-28',
          subtaskIds: ['HR-115', 'HR-116', 'HR-117'],
          commentItems: [
            {
              id: 'c1',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Should we include a section on co-working space stipends?',
              time: '2h ago',
            },
            {
              id: 'c2',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: "Good idea — I'll add it to the draft. Also checking what competitors offer.",
              time: '1h ago',
            },
            {
              id: 'c3',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Legal flagged we need to update the liability clause for remote injuries.',
              time: '30m ago',
            },
          ],
          fileItems: [{ id: 'f1', name: 'Current_Remote_Policy_v2.pdf', size: '245 KB', type: 'pdf' }],
        },
        {
          id: 'HR-102',
          title: 'Research employee wellness platforms',
          priority: 'low',
          assignee: assignees.carol,
          tags: [tagPresets.benefits],
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-103',
          title: 'Create training calendar for new hires',
          priority: 'medium',
          assignee: assignees.frank,
          tags: [tagPresets.training, tagPresets.onboarding],
          dueDate: '2026-04-05',
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Can we integrate this with the existing LMS?',
              time: '1d ago',
            },
            {
              id: 'c2',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Looking into it — the API supports calendar sync.',
              time: '22h ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Training_Modules_List.xlsx', size: '128 KB', type: 'spreadsheet' },
            { id: 'f2', name: 'Onboarding_Flow_Diagram.png', size: '1.2 MB', type: 'image' },
            { id: 'f3', name: 'LMS_Integration_Notes.pdf', size: '89 KB', type: 'pdf' },
          ],
        },
        {
          id: 'HR-116',
          title: 'Benchmark 5 competitor policies',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-117',
          title: 'Draft proposed changes document',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'todo',
      title: 'To Do',
      color: 'text-blue-600 dark:text-blue-400',
      dotColor: 'bg-blue-500',
      tasks: [
        {
          id: 'HR-104',
          title: 'Set up interviews for Senior Designer role',
          description: 'Coordinate with hiring panel, schedule 4 candidates',
          priority: 'high',
          assignee: assignees.bob,
          tags: [tagPresets.recruitment],
          dueDate: '2026-03-15',
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Candidate #3 requested to reschedule to Thursday.',
              time: '3d ago',
            },
            {
              id: 'c2',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Updated. Thursday 2pm works for everyone.',
              time: '3d ago',
            },
            {
              id: 'c3',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Portfolio review links are ready — shared in the hiring channel.',
              time: '2d ago',
            },
            {
              id: 'c4',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: "Thanks Eva. I'll add those to the scorecards.",
              time: '2d ago',
            },
            {
              id: 'c5',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Can we include a design challenge? 30 min whiteboard session.',
              time: '1d ago',
            },
            {
              id: 'c6',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Good call — added to the schedule after the panel round.',
              time: '1d ago',
            },
            {
              id: 'c7',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: "All set. Let's sync after the first two interviews.",
              time: '5h ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Interview_Rubric_Sr_Designer.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f2', name: 'Candidate_Profiles.xlsx', size: '342 KB', type: 'spreadsheet' },
          ],
        },
        {
          id: 'HR-105',
          title: 'Process March payroll adjustments',
          priority: 'urgent',
          assignee: assignees.eva,
          tags: [tagPresets.payroll],
          dueDate: '2026-03-12',
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Three employees reported incorrect overtime — investigating.',
              time: '4h ago',
            },
          ],
          fileItems: [],
        },
        {
          id: 'HR-106',
          title: 'Update employee handbook — Section 4.2',
          priority: 'medium',
          assignee: assignees.david,
          tags: [tagPresets.compliance, tagPresets.policy],
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Section 4.2 needs to reflect the new PTO rollover rules.',
              time: '2d ago',
            },
            {
              id: 'c2',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Also update the bereavement leave policy — legal sent revisions.',
              time: '1d ago',
            },
            {
              id: 'c3',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'I can review the final draft before publishing.',
              time: '12h ago',
            },
            {
              id: 'c4',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Thanks Frank. Will have it ready by EOD tomorrow.',
              time: '10h ago',
            },
          ],
          fileItems: [{ id: 'f1', name: 'Handbook_Section4.2_Draft.pdf', size: '198 KB', type: 'pdf' }],
        },
        {
          id: 'HR-107',
          title: 'Review benefits enrollment for new joiners',
          priority: 'low',
          assignee: assignees.carol,
          tags: [tagPresets.benefits, tagPresets.onboarding],
          dueDate: '2026-03-20',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      color: 'text-orange-600 dark:text-orange-400',
      dotColor: 'bg-orange-500',
      tasks: [
        {
          id: 'HR-108',
          title: 'Onboard 3 new engineers — Week 2 orientation',
          description: 'Equipment setup, system access, team introductions',
          priority: 'high',
          assignee: assignees.alice,
          tags: [tagPresets.onboarding],
          dueDate: '2026-03-14',
          subtaskIds: ['HR-118', 'HR-119', 'HR-120'],
          commentItems: [
            {
              id: 'c1',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'All three laptops are configured and ready for pickup.',
              time: '3d ago',
            },
            {
              id: 'c2',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: "GitHub access granted. They're in the eng-new-hires team.",
              time: '3d ago',
            },
            {
              id: 'c3',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Team intro meetings scheduled for Tuesday and Wednesday.',
              time: '2d ago',
            },
            {
              id: 'c4',
              author: 'Carol White',
              authorColor: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
              text: 'Benefits enrollment forms sent to all three.',
              time: '2d ago',
            },
            {
              id: 'c5',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'One engineer had issues with VPN — IT is looking into it.',
              time: '1d ago',
            },
            {
              id: 'c6',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'VPN issue resolved — was a firewall config on their end.',
              time: '1d ago',
            },
            {
              id: 'c7',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Payroll records created for all three. Direct deposit pending.',
              time: '20h ago',
            },
            {
              id: 'c8',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Assigned buddies: Sarah→James, Mike→Priya, Tom→Alex.',
              time: '16h ago',
            },
            {
              id: 'c9',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Great progress! Just HR paperwork and feedback survey left.',
              time: '8h ago',
            },
            {
              id: 'c10',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Week 1 feedback from all three was very positive.',
              time: '4h ago',
            },
            {
              id: 'c11',
              author: 'Carol White',
              authorColor: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
              text: 'Two out of three have completed benefits enrollment.',
              time: '2h ago',
            },
            {
              id: 'c12',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Following up with the third one today. Should be done by EOD.',
              time: '1h ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Onboarding_Checklist_Engineers.pdf', size: '312 KB', type: 'pdf' },
            { id: 'f2', name: 'Equipment_Inventory.xlsx', size: '87 KB', type: 'spreadsheet' },
            { id: 'f3', name: 'Team_Org_Chart.png', size: '456 KB', type: 'image' },
            { id: 'f4', name: 'VPN_Setup_Guide.pdf', size: '1.1 MB', type: 'pdf' },
            { id: 'f5', name: 'Benefits_Enrollment_Form.pdf', size: '234 KB', type: 'pdf' },
          ],
        },
        {
          id: 'HR-109',
          title: 'Conduct annual compliance training',
          priority: 'high',
          assignee: assignees.frank,
          tags: [tagPresets.training, tagPresets.compliance],
          dueDate: '2026-03-18',
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Slide deck updated with new data privacy regulations.',
              time: '2d ago',
            },
            {
              id: 'c2',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Can we make Session A virtual for remote engineers?',
              time: '1d ago',
            },
            {
              id: 'c3',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Yes — setting up a hybrid session with Zoom link.',
              time: '18h ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Compliance_Training_2026.pdf', size: '2.4 MB', type: 'pdf' },
            { id: 'f2', name: 'Acknowledgment_Form_Template.pdf', size: '67 KB', type: 'pdf' },
          ],
        },
        {
          id: 'HR-110',
          title: 'Prepare performance review templates',
          priority: 'medium',
          assignee: assignees.david,
          tags: [tagPresets.policy],
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: "Using last year's template as a starting point. Adding peer review section.",
              time: '3d ago',
            },
            {
              id: 'c2',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Can we add a self-assessment section too?',
              time: '2d ago',
            },
            {
              id: 'c3',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Good idea — adding it. Also including a goals section for next quarter.',
              time: '2d ago',
            },
            {
              id: 'c4',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: "Please share a preview before we roll out. Last year's had confusing rating scales.",
              time: '1d ago',
            },
            {
              id: 'c5',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Will share draft by Friday. Simplified the scale to 1-5 with clear descriptions.',
              time: '8h ago',
            },
          ],
          fileItems: [{ id: 'f1', name: 'Review_Template_Draft_v3.pdf', size: '178 KB', type: 'pdf' }],
        },
        {
          id: 'HR-120',
          title: 'Complete HR paperwork and benefits enrollment',
          priority: 'medium',
          assignee: assignees.carol,
          tags: [],
          parentId: 'HR-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'in-review',
      title: 'In Review',
      color: 'text-violet-600 dark:text-violet-400',
      dotColor: 'bg-violet-500',
      tasks: [
        {
          id: 'HR-111',
          title: 'Finalize job descriptions for Q2 hiring plan',
          priority: 'high',
          assignee: assignees.bob,
          tags: [tagPresets.recruitment],
          dueDate: '2026-03-13',
          subtaskIds: ['HR-121', 'HR-122', 'HR-123'],
          commentItems: [
            {
              id: 'c1',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'All six JDs are drafted. Sending to hiring managers for review.',
              time: '4d ago',
            },
            {
              id: 'c2',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Salary ranges confirmed for all positions. Updated the comp spreadsheet.',
              time: '3d ago',
            },
            {
              id: 'c3',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'DevOps JD needs to mention Kubernetes experience. Updated.',
              time: '3d ago',
            },
            {
              id: 'c4',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: "Looks great overall. Let's get legal to sign off.",
              time: '2d ago',
            },
            {
              id: 'c5',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Legal review submitted. ETA is end of day Thursday.',
              time: '1d ago',
            },
            {
              id: 'c6',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Should we add remote/hybrid designation to each JD?',
              time: '1d ago',
            },
            {
              id: 'c7',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Good point — added work location to all six.',
              time: '20h ago',
            },
            {
              id: 'c8',
              author: 'Carol White',
              authorColor: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
              text: 'Benefits section should mention the new wellness stipend.',
              time: '12h ago',
            },
            {
              id: 'c9',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Done! All JDs now include the wellness benefit.',
              time: '6h ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Q2_Job_Descriptions_All.pdf', size: '892 KB', type: 'pdf' },
            { id: 'f2', name: 'Salary_Benchmarks_Q2.xlsx', size: '234 KB', type: 'spreadsheet' },
            { id: 'f3', name: 'Hiring_Plan_Timeline.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f4', name: 'Org_Chart_Q2_Projected.png', size: '678 KB', type: 'image' },
          ],
        },
        {
          id: 'HR-112',
          title: 'Audit PTO balances before rollover deadline',
          priority: 'urgent',
          assignee: assignees.eva,
          tags: [tagPresets.payroll, tagPresets.compliance],
          dueDate: '2026-03-11',
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Found 12 employees with balances exceeding the rollover cap.',
              time: '2d ago',
            },
            {
              id: 'c2',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Send them reminders to use or forfeit before the 11th.',
              time: '2d ago',
            },
            {
              id: 'c3',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Reminders sent. 8 have acknowledged so far.',
              time: '1d ago',
            },
            {
              id: 'c4',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Do we need manager approval for the remaining 4?',
              time: '1d ago',
            },
            {
              id: 'c5',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Yes — escalated to their managers. Following up today.',
              time: '6h ago',
            },
            {
              id: 'c6',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Two more responded. Just 2 remaining.',
              time: '2h ago',
            },
          ],
          fileItems: [{ id: 'f1', name: 'PTO_Audit_Report_March.xlsx', size: '567 KB', type: 'spreadsheet' }],
        },
        {
          id: 'HR-123',
          title: 'Final legal review of all JDs',
          priority: 'high',
          assignee: assignees.bob,
          tags: [],
          parentId: 'HR-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
    {
      id: 'done',
      title: 'Done',
      color: 'text-emerald-600 dark:text-emerald-400',
      dotColor: 'bg-emerald-500',
      tasks: [
        {
          id: 'HR-113',
          title: 'Complete February payroll processing',
          priority: 'high',
          assignee: assignees.eva,
          tags: [tagPresets.payroll],
          subtaskIds: [],
          commentItems: [
            {
              id: 'c1',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'All payroll calculations verified. Submitting to bank.',
              time: '5d ago',
            },
            {
              id: 'c2',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Confirmed — all deposits went through successfully.',
              time: '4d ago',
            },
            {
              id: 'c3',
              author: 'Carol White',
              authorColor: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
              text: 'Payslips generated and emailed to all employees.',
              time: '4d ago',
            },
            {
              id: 'c4',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Closing this out — February payroll is fully complete.',
              time: '3d ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Feb_Payroll_Summary.xlsx', size: '445 KB', type: 'spreadsheet' },
            { id: 'f2', name: 'Feb_Tax_Withholdings.pdf', size: '289 KB', type: 'pdf' },
          ],
        },
        {
          id: 'HR-114',
          title: 'Onboard Marketing Coordinator — Sarah Lin',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [tagPresets.onboarding],
          subtaskIds: ['HR-124', 'HR-125', 'HR-126'],
          commentItems: [
            {
              id: 'c1',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'Welcome packet sent. Sarah starts Monday!',
              time: '3w ago',
            },
            {
              id: 'c2',
              author: 'Bob Martinez',
              authorColor: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
              text: 'Workstation set up in the marketing pod. Desk 4B.',
              time: '2w ago',
            },
            {
              id: 'c3',
              author: 'Carol White',
              authorColor: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
              text: 'Benefits enrollment complete. She chose Plan B.',
              time: '2w ago',
            },
            {
              id: 'c4',
              author: 'Frank Lee',
              authorColor: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400',
              text: 'Marketing tools training done — HubSpot, Figma, Analytics.',
              time: '1w ago',
            },
            {
              id: 'c5',
              author: 'David Kim',
              authorColor: 'bg-violet-500/15 text-violet-600 dark:text-violet-400',
              text: 'Manager check-in went great. Sarah is settling in well.',
              time: '1w ago',
            },
            {
              id: 'c6',
              author: 'Eva Johnson',
              authorColor: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
              text: 'Payroll set up — first paycheck confirmed.',
              time: '5d ago',
            },
            {
              id: 'c7',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: '30-day check-in done. Very positive feedback all around.',
              time: '2d ago',
            },
            {
              id: 'c8',
              author: 'Alice Chen',
              authorColor: 'bg-orange-500/15 text-orange-600 dark:text-orange-400',
              text: 'All tasks complete — closing this onboarding ticket. \u{1F389}',
              time: '1d ago',
            },
          ],
          fileItems: [
            { id: 'f1', name: 'Offer_Letter_Sarah_Lin.pdf', size: '156 KB', type: 'pdf' },
            { id: 'f2', name: 'Welcome_Packet.pdf', size: '2.3 MB', type: 'pdf' },
            { id: 'f3', name: 'I9_Form_Signed.pdf', size: '89 KB', type: 'pdf' },
            { id: 'f4', name: 'Benefits_Selection.pdf', size: '112 KB', type: 'pdf' },
            { id: 'f5', name: 'Marketing_Tools_Access.xlsx', size: '45 KB', type: 'spreadsheet' },
            { id: 'f6', name: '30Day_Feedback_Survey.pdf', size: '78 KB', type: 'pdf' },
          ],
        },
        {
          id: 'HR-115',
          title: 'Review current remote work policy document',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-101',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-118',
          title: 'Issue laptops and peripherals',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-119',
          title: 'Set up email and Slack accounts',
          priority: 'medium',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-108',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-121',
          title: 'Senior Backend Engineer JD',
          priority: 'medium',
          assignee: assignees.bob,
          tags: [],
          parentId: 'HR-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-122',
          title: 'Product Manager JD',
          priority: 'medium',
          assignee: assignees.bob,
          tags: [],
          parentId: 'HR-111',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-124',
          title: 'Send offer letter and welcome packet',
          priority: 'low',
          assignee: assignees.alice,
          tags: [],
          parentId: 'HR-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-125',
          title: 'Set up workstation and equipment',
          priority: 'low',
          assignee: assignees.bob,
          tags: [],
          parentId: 'HR-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
        {
          id: 'HR-126',
          title: 'Benefits enrollment',
          priority: 'low',
          assignee: assignees.carol,
          tags: [],
          parentId: 'HR-114',
          subtaskIds: [],
          commentItems: [],
          fileItems: [],
        },
      ],
    },
  ]
}
