import { defineRegistryItem } from '../../lib/define-registry'

export default defineRegistryItem({
  name: 'kanban-task-board',
  type: 'registry:block',
  categories: ['productivity', 'dashboard', 'data'],
  description:
    'Full kanban task board surface: 4 status columns, drag-and-drop card movement with insertion indicator, board/list view toggle, search + priority + assignee filters, collapsible columns, click-to-open task detail Sheet (comments, subtasks, files), full-form Add Task Dialog with priority/assignee/due-date/tags/subtasks. Mega-block: ships 14 Vue files (KanbanBoard + 6 kanban-* views + 7 small badges/lists). Bind with v-model:columns; consumer owns the columns array so swapping the in-memory store for Drizzle/Postgres is a one-line change. Auto-pulls the use-kanban hook (types + configs + helpers) and kanban-data lib (seed columns).',
  files: [
    { path: 'KanbanBoard.vue', target: 'components/blocks/kanban-task-board/KanbanBoard.vue' },
    { path: 'SimpleKanban.vue', target: 'components/blocks/kanban-task-board/SimpleKanban.vue' },
    { path: 'KanbanCard.vue', target: 'components/blocks/kanban-task-board/KanbanCard.vue' },
    { path: 'KanbanColumn.vue', target: 'components/blocks/kanban-task-board/KanbanColumn.vue' },
    { path: 'KanbanListView.vue', target: 'components/blocks/kanban-task-board/KanbanListView.vue' },
    { path: 'KanbanTaskSheet.vue', target: 'components/blocks/kanban-task-board/KanbanTaskSheet.vue' },
    { path: 'KanbanAddTaskDialog.vue', target: 'components/blocks/kanban-task-board/KanbanAddTaskDialog.vue' },
    { path: 'KanbanToolbar.vue', target: 'components/blocks/kanban-task-board/KanbanToolbar.vue' },
    { path: 'PriorityBadge.vue', target: 'components/blocks/kanban-task-board/PriorityBadge.vue' },
    { path: 'DueDateBadge.vue', target: 'components/blocks/kanban-task-board/DueDateBadge.vue' },
    { path: 'TagBadge.vue', target: 'components/blocks/kanban-task-board/TagBadge.vue' },
    { path: 'UserAvatar.vue', target: 'components/blocks/kanban-task-board/UserAvatar.vue' },
    { path: 'SubtaskProgress.vue', target: 'components/blocks/kanban-task-board/SubtaskProgress.vue' },
    { path: 'SubtaskList.vue', target: 'components/blocks/kanban-task-board/SubtaskList.vue' },
    { path: 'CommentList.vue', target: 'components/blocks/kanban-task-board/CommentList.vue' },
    { path: 'link-injection.ts', target: 'components/blocks/kanban-task-board/link-injection.ts' },
  ],
  dependencies: ['lucide-vue-next', '@internationalized/date', 'reka-ui'],
  registryDependencies: [
    'https://uipkge.dev/r/use-kanban.json',
    'https://uipkge.dev/r/kanban-data.json',
    'https://uipkge.dev/r/page.json',
    'https://uipkge.dev/r/card.json',
    'https://uipkge.dev/r/button.json',
    'https://uipkge.dev/r/badge.json',
    'https://uipkge.dev/r/input.json',
    'https://uipkge.dev/r/label.json',
    'https://uipkge.dev/r/select.json',
    'https://uipkge.dev/r/sheet.json',
    'https://uipkge.dev/r/dialog.json',
    'https://uipkge.dev/r/popover.json',
    'https://uipkge.dev/r/calendar.json',
    'https://uipkge.dev/r/dropdown-menu.json',
    'https://uipkge.dev/r/tooltip.json',
    'https://uipkge.dev/r/avatar.json',
    'https://uipkge.dev/r/toggle-group.json',
    'https://uipkge.dev/r/rich-text-editor.json',
  ],
})
