import { defineRegistryItem } from '../../lib/define-registry'

// Meta-bundle. Installing `@uipkge/charts` pulls every Angular chart wrapper
// via registryDependencies. Each chart is also independently installable (see
// `<chart>.registry.ts` files in sibling dirs).
export default defineRegistryItem({
  name: 'charts',
  type: 'registry:ui',
  categories: ['charts'],
  framework: 'angular',
  description:
    'Meta-bundle that installs every Angular chart wrapper at once — all 66 standalone ECharts components with data/option inputs, theme-aware via registry tokens.',
  files: [],
  dependencies: [],
  registryDependencies: [
    'https://uipkge.dev/r/alluvial-chart.json',
    'https://uipkge.dev/r/area-chart.json',
    'https://uipkge.dev/r/bar-chart.json',
    'https://uipkge.dev/r/bar-race-chart.json',
    'https://uipkge.dev/r/beeswarm-chart.json',
    'https://uipkge.dev/r/boxplot-chart.json',
    'https://uipkge.dev/r/bubble-chart.json',
    'https://uipkge.dev/r/bubble-map.json',
    'https://uipkge.dev/r/bullet-chart.json',
    'https://uipkge.dev/r/calendar-heatmap.json',
    'https://uipkge.dev/r/candlestick-chart.json',
    'https://uipkge.dev/r/category-distribution-chart.json',
    'https://uipkge.dev/r/chord-chart.json',
    'https://uipkge.dev/r/choropleth-map-chart.json',
    'https://uipkge.dev/r/combo-chart.json',
    'https://uipkge.dev/r/control-chart.json',
    'https://uipkge.dev/r/donut-chart.json',
    'https://uipkge.dev/r/dotted-map-chart.json',
    'https://uipkge.dev/r/dumbbell-chart.json',
    'https://uipkge.dev/r/effect-scatter-chart.json',
    'https://uipkge.dev/r/error-bar-chart.json',
    'https://uipkge.dev/r/funnel-chart.json',
    'https://uipkge.dev/r/gantt-chart.json',
    'https://uipkge.dev/r/gauge-chart.json',
    'https://uipkge.dev/r/graph-chart.json',
    'https://uipkge.dev/r/heatmap.json',
    'https://uipkge.dev/r/heikin-ashi-chart.json',
    'https://uipkge.dev/r/hexbin-map.json',
    'https://uipkge.dev/r/histogram-chart.json',
    'https://uipkge.dev/r/icicle-chart.json',
    'https://uipkge.dev/r/line-chart.json',
    'https://uipkge.dev/r/liquid-fill-chart.json',
    'https://uipkge.dev/r/lollipop-chart.json',
    'https://uipkge.dev/r/marimekko-chart.json',
    'https://uipkge.dev/r/nightingale-chart.json',
    'https://uipkge.dev/r/parallel-chart.json',
    'https://uipkge.dev/r/pareto-chart.json',
    'https://uipkge.dev/r/pictorial-bar-chart.json',
    'https://uipkge.dev/r/pie-chart.json',
    'https://uipkge.dev/r/polar-bar-chart.json',
    'https://uipkge.dev/r/population-pyramid-chart.json',
    'https://uipkge.dev/r/progress-ring-chart.json',
    'https://uipkge.dev/r/quadrant-chart.json',
    'https://uipkge.dev/r/radar-chart.json',
    'https://uipkge.dev/r/range-area-chart.json',
    'https://uipkge.dev/r/range-bar-chart.json',
    'https://uipkge.dev/r/raw-chart.json',
    'https://uipkge.dev/r/route-flow-map.json',
    'https://uipkge.dev/r/sankey-chart.json',
    'https://uipkge.dev/r/scatter-chart.json',
    'https://uipkge.dev/r/segmented-gauge.json',
    'https://uipkge.dev/r/slope-chart.json',
    'https://uipkge.dev/r/smooth-funnel.json',
    'https://uipkge.dev/r/sparkline.json',
    'https://uipkge.dev/r/stacked-area-chart.json',
    'https://uipkge.dev/r/stacked-bar-chart.json',
    'https://uipkge.dev/r/sunburst-chart.json',
    'https://uipkge.dev/r/theme-river.json',
    'https://uipkge.dev/r/tree-chart.json',
    'https://uipkge.dev/r/treemap-chart.json',
    'https://uipkge.dev/r/uptime-tracker-chart.json',
    'https://uipkge.dev/r/vector-map.json',
    'https://uipkge.dev/r/violin-chart.json',
    'https://uipkge.dev/r/waffle-chart.json',
    'https://uipkge.dev/r/waterfall-chart.json',
    'https://uipkge.dev/r/word-cloud-chart.json',
  ],
})
