export { default as Sidebar, type SidebarProps } from './Sidebar.svelte'
export { default as SidebarContent, type SidebarContentProps } from './SidebarContent.svelte'
export { default as SidebarFooter, type SidebarFooterProps } from './SidebarFooter.svelte'
export { default as SidebarGroup, type SidebarGroupProps } from './SidebarGroup.svelte'
export { default as SidebarGroupAction, type SidebarGroupActionProps } from './SidebarGroupAction.svelte'
export { default as SidebarGroupContent, type SidebarGroupContentProps } from './SidebarGroupContent.svelte'
export { default as SidebarGroupLabel, type SidebarGroupLabelProps } from './SidebarGroupLabel.svelte'
export { default as SidebarHeader, type SidebarHeaderProps } from './SidebarHeader.svelte'
export { default as SidebarInput, type SidebarInputProps } from './SidebarInput.svelte'
export { default as SidebarInset, type SidebarInsetProps } from './SidebarInset.svelte'
export { default as SidebarMenu, type SidebarMenuProps } from './SidebarMenu.svelte'
export { default as SidebarMenuAction, type SidebarMenuActionProps } from './SidebarMenuAction.svelte'
export { default as SidebarMenuBadge, type SidebarMenuBadgeProps } from './SidebarMenuBadge.svelte'
export { default as SidebarMenuButton, type SidebarMenuButtonProps } from './SidebarMenuButton.svelte'
export { default as SidebarMenuItem, type SidebarMenuItemProps } from './SidebarMenuItem.svelte'
export { default as SidebarMenuSkeleton, type SidebarMenuSkeletonProps } from './SidebarMenuSkeleton.svelte'
export { default as SidebarMenuSub, type SidebarMenuSubProps } from './SidebarMenuSub.svelte'
export { default as SidebarMenuSubButton, type SidebarMenuSubButtonProps } from './SidebarMenuSubButton.svelte'
export { default as SidebarMenuSubItem, type SidebarMenuSubItemProps } from './SidebarMenuSubItem.svelte'
export { default as SidebarProvider, type SidebarProviderProps } from './SidebarProvider.svelte'
export { default as SidebarRail, type SidebarRailProps } from './SidebarRail.svelte'
export { default as SidebarSeparator, type SidebarSeparatorProps } from './SidebarSeparator.svelte'
export { default as SidebarTrigger, type SidebarTriggerProps } from './SidebarTrigger.svelte'

export { useSidebar } from './utils'

// Re-export variant API from the sibling file (kept separate to avoid the
// Component.svelte <-> index.ts circular import that broke dev SSR for Card).
export { sidebarMenuButtonVariants, type SidebarMenuButtonVariants } from './sidebar.variants'
