import { defineRegistryItem } from '../../lib/define-registry'

export default defineRegistryItem({
  name: 'sidebar',
  type: 'registry:ui',
  categories: ['navigation'],
  framework: 'svelte',
  description:
    'Full-height app sidebar — collapsible to icons, with grouping, sub-grouping, and integrated search. The navigation surface for product apps with many sections.',
  files: [
    { path: 'Sidebar.svelte', target: 'components/ui/sidebar/Sidebar.svelte' },
    { path: 'SidebarContent.svelte', target: 'components/ui/sidebar/SidebarContent.svelte' },
    { path: 'SidebarFooter.svelte', target: 'components/ui/sidebar/SidebarFooter.svelte' },
    { path: 'SidebarGroup.svelte', target: 'components/ui/sidebar/SidebarGroup.svelte' },
    { path: 'SidebarGroupAction.svelte', target: 'components/ui/sidebar/SidebarGroupAction.svelte' },
    { path: 'SidebarGroupContent.svelte', target: 'components/ui/sidebar/SidebarGroupContent.svelte' },
    { path: 'SidebarGroupLabel.svelte', target: 'components/ui/sidebar/SidebarGroupLabel.svelte' },
    { path: 'SidebarHeader.svelte', target: 'components/ui/sidebar/SidebarHeader.svelte' },
    { path: 'SidebarInput.svelte', target: 'components/ui/sidebar/SidebarInput.svelte' },
    { path: 'SidebarInset.svelte', target: 'components/ui/sidebar/SidebarInset.svelte' },
    { path: 'SidebarMenu.svelte', target: 'components/ui/sidebar/SidebarMenu.svelte' },
    { path: 'SidebarMenuAction.svelte', target: 'components/ui/sidebar/SidebarMenuAction.svelte' },
    { path: 'SidebarMenuBadge.svelte', target: 'components/ui/sidebar/SidebarMenuBadge.svelte' },
    { path: 'SidebarMenuButton.svelte', target: 'components/ui/sidebar/SidebarMenuButton.svelte' },
    { path: 'SidebarMenuButtonChild.svelte', target: 'components/ui/sidebar/SidebarMenuButtonChild.svelte' },
    { path: 'SidebarMenuItem.svelte', target: 'components/ui/sidebar/SidebarMenuItem.svelte' },
    { path: 'SidebarMenuSkeleton.svelte', target: 'components/ui/sidebar/SidebarMenuSkeleton.svelte' },
    { path: 'SidebarMenuSub.svelte', target: 'components/ui/sidebar/SidebarMenuSub.svelte' },
    { path: 'SidebarMenuSubButton.svelte', target: 'components/ui/sidebar/SidebarMenuSubButton.svelte' },
    { path: 'SidebarMenuSubItem.svelte', target: 'components/ui/sidebar/SidebarMenuSubItem.svelte' },
    { path: 'SidebarProvider.svelte', target: 'components/ui/sidebar/SidebarProvider.svelte' },
    { path: 'SidebarRail.svelte', target: 'components/ui/sidebar/SidebarRail.svelte' },
    { path: 'SidebarSeparator.svelte', target: 'components/ui/sidebar/SidebarSeparator.svelte' },
    { path: 'SidebarTrigger.svelte', target: 'components/ui/sidebar/SidebarTrigger.svelte' },
    { path: 'sidebar.variants.ts', target: 'components/ui/sidebar/sidebar.variants.ts' },
    { path: 'index.ts', target: 'components/ui/sidebar/index.ts' },
    { path: 'utils.ts', target: 'components/ui/sidebar/utils.ts' },
  ],
  dependencies: ['@lucide/svelte', 'class-variance-authority'],
  registryDependencies: [
    'https://uipkge.dev/r/button.json',
    'https://uipkge.dev/r/input.json',
    'https://uipkge.dev/r/separator.json',
    'https://uipkge.dev/r/sheet.json',
    'https://uipkge.dev/r/skeleton.json',
    'https://uipkge.dev/r/tooltip.json',
  ],
})
